#!/usr/bin/env bash
#
# ⚡ Cipher OS — Automated Installer
# ------------------------------------------------------------------
# Sets up PHP config, MySQL database, and default admin account
# with a single command.
#
# Usage:
#   ./install.sh
#   ./install.sh --host localhost --user root --pass "" --name cipher_os --no-serve
#
# ------------------------------------------------------------------

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────
C_RESET='\033[0m'
C_CYAN='\033[0;36m'
C_GREEN='\033[0;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[0;31m'
C_BOLD='\033[1m'

info()  { echo -e "${C_CYAN}▸${C_RESET} $1"; }
ok()    { echo -e "${C_GREEN}✔${C_RESET} $1"; }
warn()  { echo -e "${C_YELLOW}⚠${C_RESET} $1"; }
error() { echo -e "${C_RED}✘${C_RESET} $1"; }

banner() {
cat << "EOF"

   ⚡ ═══════════════════════════════════════════ ⚡
             C I P H E R   O S   —   S E T U P
   ⚡ ═══════════════════════════════════════════ ⚡

EOF
}

# ── Defaults (overridable via flags) ─────────────────────────────────
DB_HOST="localhost"
DB_USER="root"
DB_PASS=""
DB_NAME="cipher_os"
SERVE=true
PORT=8000

# ── Parse flags ───────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) DB_HOST="$2"; shift 2 ;;
    --user) DB_USER="$2"; shift 2 ;;
    --pass) DB_PASS="$2"; shift 2 ;;
    --name) DB_NAME="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --no-serve) SERVE=false; shift ;;
    -h|--help)
      echo "Usage: ./install.sh [--host HOST] [--user USER] [--pass PASS] [--name DBNAME] [--port PORT] [--no-serve]"
      exit 0
      ;;
    *) error "Unknown option: $1"; exit 1 ;;
  esac
done

banner

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Step 1: Check requirements ───────────────────────────────────────
info "Checking requirements..."

if ! command -v php >/dev/null 2>&1; then
    error "PHP is not installed."
    echo "   Install it first, e.g.:"
    echo "     Fedora/RHEL : sudo dnf install php-cli php-mysqlnd"
    echo "     Debian/Ubuntu: sudo apt install php-cli php-mysql"
    exit 1
fi
PHP_VERSION=$(php -r 'echo PHP_VERSION;')
ok "PHP $PHP_VERSION found"

if ! command -v mysql >/dev/null 2>&1; then
    warn "MySQL client not found — will still try via PHP, but you may need to install 'mysql-client' or 'mariadb'."
else
    ok "MySQL client found"
fi

if ! php -m | grep -qi mysqli; then
    error "PHP mysqli extension is missing. Install php-mysqlnd (Fedora) or php-mysql (Debian/Ubuntu)."
    exit 1
fi
ok "PHP mysqli extension enabled"

# ── Step 2: Interactive prompts (skip if flags were given) ──────────
echo ""
info "Database configuration (press Enter to accept the default in brackets):"

read -rp "  DB Host [$DB_HOST]: " input && DB_HOST="${input:-$DB_HOST}"
read -rp "  DB User [$DB_USER]: " input && DB_USER="${input:-$DB_USER}"
read -rp "  DB Password [hidden, Enter for none]: " -s DB_PASS_INPUT
echo ""
[[ -n "$DB_PASS_INPUT" ]] && DB_PASS="$DB_PASS_INPUT"
read -rp "  DB Name [$DB_NAME]: " input && DB_NAME="${input:-$DB_NAME}"

# ── Step 3: Write .dbconfig.php ──────────────────────────────────────
echo ""
info "Writing database configuration to cipher-core/.dbconfig.php ..."

cat > "$SCRIPT_DIR/cipher-core/.dbconfig.php" << PHP
<?php
// Auto-generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
// ⚠️ Do NOT commit this file to a public repository.
return [
    'host' => '$DB_HOST',
    'user' => '$DB_USER',
    'pass' => '$DB_PASS',
    'name' => '$DB_NAME',
];
PHP

ok "Config written"

# Make sure it's gitignored
if [[ -f "$SCRIPT_DIR/.gitignore" ]]; then
    grep -qxF 'cipher-core/.dbconfig.php' "$SCRIPT_DIR/.gitignore" || echo 'cipher-core/.dbconfig.php' >> "$SCRIPT_DIR/.gitignore"
fi

# ── Step 4: Generate a secure random admin password ──────────────────
ADMIN_PASS=$(php -r 'echo bin2hex(random_bytes(6));')
ADMIN_HASH=$(php -r "echo password_hash('$ADMIN_PASS', PASSWORD_DEFAULT);")

info "Generating a secure random admin password..."
ok "Admin password generated"

# Generate a separate secret for the standalone admin.php notice/activity panel
PANEL_SECRET=$(php -r 'echo bin2hex(random_bytes(8));')
cat > "$SCRIPT_DIR/cipher-core/.admin_panel_secret.php" << PHP
<?php
// Auto-generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
// ⚠️ Do NOT commit this file to a public repository.
return '$PANEL_SECRET';
PHP
if [[ -f "$SCRIPT_DIR/.gitignore" ]]; then
    grep -qxF 'cipher-core/.admin_panel_secret.php' "$SCRIPT_DIR/.gitignore" || echo 'cipher-core/.admin_panel_secret.php' >> "$SCRIPT_DIR/.gitignore"
fi
ok "Admin panel (admin.php) secret generated"

# Patch users_schema.sql with the fresh hash before running installer
TMP_SCHEMA=$(mktemp)
php -r '
$file = $argv[1];
$hash = $argv[2];
$sql = file_get_contents($file);
$sql = preg_replace_callback(
    "/VALUES \(.admin., .[^\047]*., .admin.\)/",
    function($m) use ($hash) {
        return "VALUES (\x27admin\x27, \x27" . $hash . "\x27, \x27admin\x27)";
    },
    $sql
);
file_put_contents($argv[3], $sql);
' "$SCRIPT_DIR/cipher-core/users_schema.sql" "$ADMIN_HASH" "$TMP_SCHEMA"
cp "$TMP_SCHEMA" "$SCRIPT_DIR/cipher-core/users_schema.sql"
rm -f "$TMP_SCHEMA"

# ── Step 5: Run the PHP installer (creates DB + tables) ──────────────
echo ""
info "Running database installer (creates database + tables)..."

if php "$SCRIPT_DIR/install.php" > /tmp/cipheros_install.log 2>&1; then
    ok "Database and tables created"
else
    error "Installer failed — see details below:"
    cat /tmp/cipheros_install.log
    exit 1
fi

# Extract a short summary from the installer log (strip HTML tags)
grep -oE '✅[^<]*' /tmp/cipheros_install.log | sed 's/<[^>]*>//g' | while read -r line; do
    echo "   $line"
done

# ── Step 6: Remove the now-unnecessary web installer for safety ──────
echo ""
read -rp "Delete install.php now for security? [Y/n]: " del_choice
if [[ "${del_choice:-Y}" =~ ^[Yy]$ ]]; then
    rm -f "$SCRIPT_DIR/install.php"
    ok "install.php removed"
else
    warn "Remember to delete install.php manually before going to production!"
fi

# ── Step 7: Set safe permissions on upload directories ───────────────
info "Setting permissions on upload/cache directories..."
find "$SCRIPT_DIR" -type d -iname "uploads" -exec chmod 755 {} \; 2>/dev/null || true
ok "Permissions set"

# ── Done ──────────────────────────────────────────────────────────────
echo ""
echo -e "${C_BOLD}${C_GREEN}════════════════════════════════════════════${C_RESET}"
echo -e "${C_BOLD}  ✅ Cipher OS installed successfully!${C_RESET}"
echo -e "${C_BOLD}${C_GREEN}════════════════════════════════════════════${C_RESET}"
echo ""
echo -e "   ${C_BOLD}Login URL:${C_RESET}     http://localhost:$PORT/login.php"
echo -e "   ${C_BOLD}Username:${C_RESET}      admin"
echo -e "   ${C_BOLD}Password:${C_RESET}      ${C_YELLOW}$ADMIN_PASS${C_RESET}  (save this now — shown only once)"
echo ""
echo -e "   ${C_BOLD}Dashboard admin panel${C_RESET} (admin.php):"
echo -e "   ${C_BOLD}Password:${C_RESET}      ${C_YELLOW}$PANEL_SECRET${C_RESET}  (save this now — shown only once)"
echo ""
echo -e "   ${C_RED}⚠ Change this password after your first login.${C_RESET}"
echo ""

if [[ "$SERVE" == true ]]; then
    read -rp "Start the built-in PHP server now on port $PORT? [Y/n]: " serve_choice
    if [[ "${serve_choice:-Y}" =~ ^[Yy]$ ]]; then
        info "Starting server — press Ctrl+C to stop."
        php -S "localhost:$PORT"
    fi
fi
